/**
 * Apply generated strategies to the Simulation Lab
 *
 * Run AFTER scripts/strategy-lab.ts has completed:
 *   npx tsx scripts/apply-strategies.ts
 *
 * What this does:
 *   1. Reads scripts/output/built-in-strategies.ts (generated by strategy-lab.ts)
 *   2. Copies it to client/src/lib/builtInStrategies.ts
 *   3. Prints a summary of the applied strategies
 */

import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const SRC  = path.join(__dirname, "output", "built-in-strategies.ts");
const DEST = path.join(__dirname, "..", "client", "src", "lib", "builtInStrategies.ts");
const JSON_SRC = path.join(__dirname, "output", "strategy-lab-results.json");

async function main() {
  // Check source exists
  if (!fs.existsSync(SRC)) {
    console.error(`\n[ERROR] Generated file not found: ${SRC}`);
    console.error("Run strategy lab first:  npx tsx scripts/strategy-lab.ts\n");
    process.exit(1);
  }

  // Copy
  fs.mkdirSync(path.dirname(DEST), { recursive: true });
  fs.copyFileSync(SRC, DEST);
  console.log(`\n✓ Copied generated strategies to:\n  ${DEST}`);

  // Print summary from results JSON
  if (fs.existsSync(JSON_SRC)) {
    const results = JSON.parse(fs.readFileSync(JSON_SRC, "utf-8"));
    const validated = results.validatedResults ?? [];
    if (validated.length > 0) {
      console.log("\nStrategies now available in the Simulation Lab:");
      console.log("─".repeat(60));
      for (const v of validated) {
        if (v.fullReturnPct === undefined) continue;
        console.log(
          `  ${v.name.padEnd(42)}  ` +
          `ret=${v.fullReturnPct?.toFixed(1)}%  sharpe=${v.fullSharpe?.toFixed(2)}`
        );
      }
    }
  }

  console.log(`
✓ Done. Restart the dev server to pick up the new presets.
  The "Pro Presets" panel in the Simulation Lab will now show these strategies.
`);
}

main().catch(err => { console.error("[FATAL]", err); process.exit(1); });
